name: Changeset Automation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

jobs:
  auto-changeset:
    #  TODO: remove true after testing is done
    if: |
      startsWith(github.repository, 'asyncapi/') &&
      ( startsWith(github.event.pull_request.title, 'fix:') ||
        startsWith(github.event.pull_request.title, 'feat:') ||
        startsWith(github.event.pull_request.title, 'fix!:') ||
        startsWith(github.event.pull_request.title, 'feat!:')
      ) || true 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Determine release type
        id: determine_release_type
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const releaseType = title.split(':')[0];
            switch (releaseType) {
              case 'fix':
                return 'patch';
              case 'feat':
                return 'minor';
              case 'fix!':
                return 'major';
              case 'feat!':
                return 'major';
              default:
                return 'patch';
            }

      - name: Create changeset file
        run: "echo -e '---\n'@asyncapi/cli': ${{ steps.determine_release_type.outputs.result }}\n---\n\n ${{ github.event.pull_request.title }}\n' > .changeset/${{ github.event.pull_request.number }}.md"

      - name: Commit changeset file
        run: |
          git config --global user.name asyncapi-bot
          git config --global user.email info@asyncapi.io
          git add .changeset/${{ github.event.pull_request.number }}.md
          # Check if there are any changes to commit
          if git diff --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "chore: add changeset for PR #${{ github.event.pull_request.number }}"
          fi

      - name: Push changeset file
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://github.com/${{ github.event.pull_request.head.repo.full_name }}
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
